### ISSUE TITLE
Week-2 Data Structures and Array Methods

### ISSUE THREAD

**Issue by 1843496** [macddmac/P3PROPHET#11]
Rivan Nayak
going to study data structures
 as well as Python List/Array Methods.
- [x] [Data Structures and Python List/Array Methods Notes](https://docs.google.com/document/d/1cOTtG30M2RCeHMZy7OqTJc3bSxzsWpxM_uvcYOFB7fc/edit?usp=sharing
Links- 

https://www.w3schools.com/python/python_ref_list.asp

https://www.geeksforgeeks.org/data-structures/

https://www.geeksforgeeks.org/overview-of-data-structures-set-1-linear-data-structures/

https://www.geeksforgeeks.org/overview-of-data-structures-set-2-binary-tree-bst-heap-and-hash/

https://www.geeksforgeeks.org/overview-of-data-structures-set-3-graph-trie-segment-tree-and-suffix-tree/

**Comment by 1843496** [comment]
I deserve a 3/3 because I put my link to my ticket as well as a link to Scrum Board on GitHub plus I put my ticket on issues as well as it has a review column. It is also visible because my ticket has my name on it which is visible for people to see that I am the one who did this ticket. Plus I also have supporting links to back my work. Lastly, I also created a google document that has all my notes in it that includes examples as well as definitions of the topics I am talking about.

**Comment by 1855481** [comment]
Jason - I believe that Rivan deserves a 3/3 because because he met all the requirements while doing them exceedingly well. For the first point Rivan earns it because he linked his issue to GitHub. Rivan earns the second point because he gave links to tangibles. Rivan earns the final point because his work is clear and concise while additionally giving it a brief description on Scrum Board.
